name: CI/CD - Build and Deploy to GitHub Pages

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          
      - name: Verify package.json and package-lock.json are in sync
        run: |
          echo "Checking if package-lock.json is in sync with package.json..."
          if ! npm ci --dry-run; then
            echo "❌ package-lock.json is out of sync with package.json"
            echo "Updating package-lock.json..."
            npm install
            echo "✅ package-lock.json updated"
          else
            echo "✅ package-lock.json is in sync"
          fi
          
      - name: Install dependencies
        run: |
          echo "Installing dependencies with npm ci..."
          npm ci
          echo "✅ Dependencies installed successfully"
        
      - name: Verify installation
        run: |
          echo "Verifying installation..."
          npm list --depth=0
          echo "✅ Installation verified"
        
      - name: Run linting
        run: |
          echo "Running ESLint..."
          npm run lint
          echo "✅ Linting passed"
        
      - name: Type check
        run: |
          echo "Running TypeScript type check..."
          npx tsc --noEmit
          echo "✅ Type check passed"
        
      - name: Build project
        run: |
          echo "Building project..."
          npm run build
          echo "✅ Build completed successfully"
        
      - name: Verify build output
        run: |
          echo "Verifying build output..."
          ls -la dist/
          if [ ! -d "dist" ] || [ ! -f "dist/index.html" ]; then
            echo "❌ Build output verification failed"
            exit 1
          fi
          echo "✅ Build output verified"
        
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ github.sha }}
          path: dist/
          retention-days: 30

  deploy:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: test-and-build
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-${{ github.sha }}
          path: dist/
          
      - name: Verify downloaded artifacts
        run: |
          echo "Verifying downloaded artifacts..."
          ls -la dist/
          if [ ! -d "dist" ] || [ ! -f "dist/index.html" ]; then
            echo "❌ Downloaded artifacts verification failed"
            exit 1
          fi
          echo "✅ Downloaded artifacts verified"
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        
      - name: Verify deployment
        run: |
          echo "Deployment completed successfully!"
          echo "URL: ${{ steps.deployment.outputs.page_url }}"
